version: "3.9"

services:
  planeja_ai_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: planejaai
      POSTGRES_DB: planeja_ai
    ports:
      - "5432:5432"
    volumes:
      -
        source: /c/git/docker/planeja_ai
        target: /var/lib/postgresql/data
        type: bind